<h1> Get content url</h1>



<form class="form-horizontal" action="<?= $this->url('foo') ?>" method="post">
    <div class="form-group">
        <label for="inputUrl" class="col-lg-2 control-label">Url</label>
        <div class="col-lg-10">
            <input type="url" class="form-control" id="inputUrl" placeholder="Url">
        </div>
    </div>

    <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>